# Generated by Django 3.0.3 on 2021-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210627_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='completed',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
