# Generated by Django 3.0.3 on 2021-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
